"use client";

import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { StyledComponentsRegistry } from "@/components/StyledComponentsRegistry/StyledComponentsRegistry";
import { GlobalStyled } from "../styles/GlobalStyled";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalStyled />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
